Reports changes + option to control device automatically
Asteliks/Modular-Building-IoT pull request #8
Opened 2021-01-20 23:39 UTC by karol-rosiak

2021-01-20 23:44 UTC, Asteliks requested changes
w dwóch miejscach zjadłeś newline

2021-01-20 23:44 UTC, Asteliks commented on Server/change_settings.php
> +</script>
newline missing

2021-01-20 23:44 UTC, Asteliks commented on Server/plot_compare.php
> +</script>
newline missing

2021-01-20 23:47 UTC, Asteliks commented
poza tym na ile to możliwe w przyszłości staraj się rozbijać zmiany na więcej commitów. Daj znać czy chcesz merga mimo braku tych newlinów

2021-01-21 00:02 UTC, karol-rosiak commented
Daj bo za późno żebym teraz to zmieniał

2021-01-21 00:22 UTC, merged